# Netlify CMS Configuration
backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - label: "Gallery Items"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
  
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General"
        name: "general"
        file: "content/settings/general.md"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Footer Text", name: "footer_text", widget: "string" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  - name: "contact_submissions"
    label: "Contact Submissions"
    folder: "content/contact"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    fields:
      - { label: "First Name", name: "first_name", widget: "string" }
      - { label: "Last Name", name: "last_name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Comments", name: "comments", widget: "text" }
      - { label: "Date Submitted", name: "date", widget: "datetime", default: "{{now}}" }